const WHATSAPP_NUMBER="5493412562123";const SEDES={rosario:{label:"Rosario",address:"Blvd. Oroño 168bis, Rosario, Santa Fe",phone:"+5493412562123",phone_display:"341 256-2123",},vgg:{label:"Villa Gobernador Gálvez",address:"Alberdi 2313, Villa Gobernador Gálvez, Santa Fe",phone:"+5493413592140",phone_display:"341 359-2140",},};let currentSede="rosario";function isMobileDevice(){return/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);}
function showToast(msg){let t=document.getElementById("miniToast");if(!t){t=document.createElement("div");t.id="miniToast";t.style.position="fixed";t.style.left="50%";t.style.bottom="24px";t.style.transform="translateX(-50%)";t.style.padding="10px 14px";t.style.borderRadius="999px";t.style.background="rgba(16,26,46,.92)";t.style.border="1px solid rgba(255,255,255,.12)";t.style.color="#eaf0ff";t.style.zIndex="9999";t.style.boxShadow="0 18px 45px rgba(0,0,0,.35)";t.style.fontWeight="700";t.style.fontSize="14px";t.style.opacity="0";t.style.transition="opacity .18s ease";document.body.appendChild(t);}
t.textContent=msg;t.style.opacity="1";clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>(t.style.opacity="0"),1400);}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true;}catch(e){return false;}}
function buildMessage(sedeKey){const sede=SEDES[sedeKey]||SEDES.rosario;return encodeURIComponent(`Hola! Quiero pedir un turno en Moreno Labari Odontología. Sede: ${sede.label}. ¿Me pasan disponibilidad?`);}
function buildCallLink(sedeKey){const sede=SEDES[sedeKey]||SEDES.rosario;return`tel:${sede.phone}`;}
function applyCallLinks(){const els=document.querySelectorAll("[data-call]");const isMobile=isMobileDevice();els.forEach((el)=>{el.onclick=null;const getSedeKey=()=>el.getAttribute("data-sede-call")||currentSede;const getSede=()=>SEDES[getSedeKey()]||SEDES.rosario;if(isMobile){const sede=getSede();el.setAttribute("href",`tel:${sede.phone}`);el.setAttribute("title",`Llamar (${sede.phone_display})`);el.textContent="Llamar";return;}
el.setAttribute("href","#");el.setAttribute("title","Copiar número");el.textContent="Copiar número";el.onclick=async(e)=>{e.preventDefault();const sede=getSede();const ok=await copyText(sede.phone_display);showToast(ok?`Número copiado: ${sede.phone_display}`:`Copiá manual: ${sede.phone_display}`);};});}
function buildWaLink(sedeKey){const sede=SEDES[sedeKey]||SEDES.rosario;const number=sede.phone.replace('+','');const msg=buildMessage(sedeKey);return`https://wa.me/${number}?text=${msg}`;}
function applyWhatsAppLinks(){const els=document.querySelectorAll("[data-wa]");els.forEach((el)=>{const sedeKey=el.getAttribute("data-sede-wa")||currentSede;el.setAttribute("href",buildWaLink(sedeKey));});}
function setActiveTabs(containerId,sedeKey){const container=document.getElementById(containerId);if(!container)return;const tabs=Array.from(container.querySelectorAll(".tab"));tabs.forEach((btn)=>{const isActive=btn.getAttribute("data-sede")===sedeKey;btn.classList.toggle("active",isActive);btn.setAttribute("aria-selected",isActive?"true":"false");});}
function togglePanels(selector,sedeKey){const panels=document.querySelectorAll(selector);panels.forEach((p)=>{const isActive=p.getAttribute("data-sede")===sedeKey;p.classList.toggle("active",isActive);p.style.display=isActive?"":"none";});}
function setSede(sedeKey){if(!SEDES[sedeKey])sedeKey="rosario";currentSede=sedeKey;const select=document.getElementById("sedeSelect");if(select)select.value=sedeKey;setActiveTabs("sedeTabs",sedeKey);setActiveTabs("contactTabs",sedeKey);togglePanels(".sedePanel",sedeKey);togglePanels(".contactAddr",sedeKey);togglePanels(".mapFrame",sedeKey);togglePanels("[data-sede-link]",sedeKey);const quick=document.getElementById("quickAddress");if(quick)quick.textContent=SEDES[sedeKey].address;applyWhatsAppLinks();applyCallLinks();if(window._syncDrawerSede)window._syncDrawerSede(sedeKey);}
function wireTabs(containerId){const container=document.getElementById(containerId);if(!container)return;container.addEventListener("click",(e)=>{const btn=e.target.closest(".tab");if(!btn)return;const sedeKey=btn.getAttribute("data-sede");if(sedeKey)setSede(sedeKey);});}
document.addEventListener("DOMContentLoaded",()=>{const select=document.getElementById("sedeSelect");if(select){select.addEventListener("change",(e)=>setSede(e.target.value));}
wireTabs("sedeTabs");wireTabs("contactTabs");setSede("rosario");const y=document.getElementById("year");if(y)y.textContent=new Date().getFullYear();});document.addEventListener('DOMContentLoaded',()=>{const revealEls=document.querySelectorAll('.reveal, .reveal-left, .reveal-right');const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}});},{threshold:0.12,rootMargin:'0px 0px -40px 0px'});revealEls.forEach(el=>observer.observe(el));const topbar=document.querySelector('.topbar');window.addEventListener('scroll',()=>{topbar.classList.toggle('scrolled',window.scrollY>20);},{passive:true});});document.addEventListener('DOMContentLoaded',()=>{const hamburger=document.getElementById('hamburgerBtn');const drawer=document.getElementById('mobileDrawer');const overlay=document.getElementById('drawerOverlay');const drawerLinks=document.querySelectorAll('.drawerLink');function openDrawer(){drawer.classList.add('open');overlay.classList.add('open');hamburger.classList.add('open');hamburger.setAttribute('aria-expanded','true');drawer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeDrawer(){drawer.classList.remove('open');overlay.classList.remove('open');hamburger.classList.remove('open');hamburger.setAttribute('aria-expanded','false');drawer.setAttribute('aria-hidden','true');document.body.style.overflow='';}
if(hamburger)hamburger.addEventListener('click',()=>{drawer.classList.contains('open')?closeDrawer():openDrawer();});if(overlay)overlay.addEventListener('click',closeDrawer);drawerLinks.forEach(link=>link.addEventListener('click',closeDrawer));const drawerSedeBtns=document.querySelectorAll('.drawerSedeBtn');drawerSedeBtns.forEach(btn=>{btn.addEventListener('click',()=>{const sedeKey=btn.getAttribute('data-sede');setSede(sedeKey);drawerSedeBtns.forEach(b=>b.classList.toggle('active',b===btn));});});window._syncDrawerSede=(sedeKey)=>{drawerSedeBtns.forEach(b=>b.classList.toggle('active',b.getAttribute('data-sede')===sedeKey));};});document.addEventListener('DOMContentLoaded',()=>{const closeBtn=document.getElementById('drawerCloseBtn');const waFloat=document.getElementById('waFloat');const drawer=document.getElementById('mobileDrawer');if(closeBtn){closeBtn.addEventListener('click',()=>{const overlay=document.getElementById('drawerOverlay');const hamburger=document.getElementById('hamburgerBtn');drawer.classList.remove('open');overlay&&overlay.classList.remove('open');hamburger&&hamburger.classList.remove('open');hamburger&&hamburger.setAttribute('aria-expanded','false');drawer.setAttribute('aria-hidden','true');document.body.style.overflow='';waFloat&&waFloat.classList.remove('drawerOpen');});}
const observer=new MutationObserver(()=>{if(drawer.classList.contains('open')){waFloat&&waFloat.classList.add('drawerOpen');}else{waFloat&&waFloat.classList.remove('drawerOpen');}});if(drawer)observer.observe(drawer,{attributes:true,attributeFilter:['class']});});document.addEventListener('DOMContentLoaded',()=>{const input=document.getElementById('obrasInput');const chips=document.querySelectorAll('#chipList .chip');const noResult=document.getElementById('obrasNoResult');if(!input)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');let visible=0;chips.forEach(chip=>{const text=(chip.dataset.obra||chip.textContent).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const match=!q||text.includes(q);chip.classList.toggle('hidden',!match);if(match)visible++;});noResult.style.display=(q&&visible===0)?'block':'none';if(noResult.style.display==='block')applyWhatsAppLinks();});});document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-ba]').forEach(slider=>{const afterWrap=slider.querySelector('.ba-after-wrap');const handle=slider.querySelector('.ba-handle');let dragging=false;function setPos(pct){pct=Math.max(5,Math.min(95,pct));afterWrap.style.clipPath=`inset(0 0 0 ${pct}%)`;handle.style.left=pct+'%';}
function getPercent(e){const rect=slider.getBoundingClientRect();const clientX=e.touches?e.touches[0].clientX:e.clientX;return((clientX-rect.left)/rect.width)*100;}
slider.addEventListener('mousedown',e=>{dragging=true;setPos(getPercent(e));e.preventDefault();});slider.addEventListener('touchstart',e=>{dragging=true;setPos(getPercent(e));},{passive:true});window.addEventListener('mousemove',e=>{if(dragging)setPos(getPercent(e));});window.addEventListener('touchmove',e=>{if(dragging)setPos(getPercent(e));},{passive:true});window.addEventListener('mouseup',()=>{dragging=false;});window.addEventListener('touchend',()=>{dragging=false;});setPos(50);});});const STORAGE_KEY='ml_reseñas_v1';function cargarReseñas(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');}
catch{return[];}}
function guardarReseñas(lista){localStorage.setItem(STORAGE_KEY,JSON.stringify(lista));}
function renderReseñas(){const grid=document.getElementById('testimGrid');const empty=document.getElementById('testimEmpty');if(!grid)return;const reseñas=cargarReseñas();if(reseñas.length===0){grid.innerHTML='';if(empty)empty.style.display='flex';return;}
if(empty)empty.style.display='none';grid.innerHTML=reseñas.map((r,i)=>{const initials=r.nombre.trim().split(' ').map(w=>w[0]).join('').slice(0,2).toUpperCase();const stars='★'.repeat(r.estrellas)+'☆'.repeat(5-r.estrellas);const delay=['delay-1','delay-2','delay-3'][i%3];return`
      <article class="testimCard reveal ${delay}">
        <div class="testimStars" aria-label="${r.estrellas} estrellas">${stars}</div>
        <p class="testimText">"${r.texto}"</p>
        <div class="testimAuthor">
          <div class="testimAvatar">${initials}</div>
          <div>
            <div class="testimName">${r.nombre}</div>
            <div class="testimMeta">Paciente · ${r.sede}</div>
          </div>
        </div>
      </article>`;}).join('');setTimeout(()=>{grid.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));},60);}
document.addEventListener('DOMContentLoaded',()=>{renderReseñas();let selectedStars=0;const starBtns=document.querySelectorAll('.starBtn');starBtns.forEach(btn=>{btn.addEventListener('click',()=>{selectedStars=parseInt(btn.dataset.star);starBtns.forEach(b=>b.classList.toggle('active',parseInt(b.dataset.star)<=selectedStars));});btn.addEventListener('mouseenter',()=>{const hov=parseInt(btn.dataset.star);starBtns.forEach(b=>b.style.color=parseInt(b.dataset.star)<=hov?'var(--gold)':'');});btn.addEventListener('mouseleave',()=>{starBtns.forEach(b=>b.style.color=parseInt(b.dataset.star)<=selectedStars?'var(--gold)':'');});});const textarea=document.getElementById('rew-text');const counter=document.getElementById('rewCharCount');if(textarea&&counter){textarea.addEventListener('input',()=>{counter.textContent=textarea.value.length;});}
const submitBtn=document.getElementById('testimSubmit');const errDiv=document.getElementById('testimFormError');const successDiv=document.getElementById('testimSuccess');const formBody=document.getElementById('testimFormBody');const resetBtn=document.getElementById('testimReset');if(submitBtn){submitBtn.addEventListener('click',()=>{const nombre=document.getElementById('rew-name').value.trim();const sede=document.getElementById('rew-sede').value;const texto=document.getElementById('rew-text').value.trim();const errors=[];if(!nombre)errors.push('Ingresá tu nombre.');if(!sede)errors.push('Elegí la sede donde te atendiste.');if(!selectedStars)errors.push('Seleccioná una puntuación.');if(!texto)errors.push('Escribí algo en tu experiencia.');if(errors.length){errDiv.style.display='block';errDiv.textContent=errors.join(' ');return;}
errDiv.style.display='none';const reseñas=cargarReseñas();reseñas.unshift({nombre,sede,estrellas:selectedStars,texto,fecha:new Date().toISOString()});guardarReseñas(reseñas);renderReseñas();formBody.style.display='none';successDiv.style.display='block';document.getElementById('testimGrid')?.scrollIntoView({behavior:'smooth',block:'start'});});}
if(resetBtn){resetBtn.addEventListener('click',()=>{document.getElementById('rew-name').value='';document.getElementById('rew-sede').value='';document.getElementById('rew-text').value='';if(counter)counter.textContent='0';selectedStars=0;starBtns.forEach(b=>{b.classList.remove('active');b.style.color='';});errDiv.style.display='none';successDiv.style.display='none';formBody.style.display='block';});}});function applyServiceLinks(){document.querySelectorAll('[data-service]').forEach(el=>{const service=el.getAttribute('data-service');const sede=SEDES[currentSede]||SEDES.rosario;const number=sede.phone.replace('+','');const msg=encodeURIComponent(`Hola! Quiero consultar sobre ${service} en Moreno Labari Odontología. Sede: ${sede.label}. ¿Me dan más información?`);el.setAttribute('href',`https://wa.me/${number}?text=${msg}`);});}
document.addEventListener('DOMContentLoaded',()=>{const sections=document.querySelectorAll('section[id]');const navLinks=document.querySelectorAll('.menu a[href^="#"]');if(!sections.length||!navLinks.length)return;const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){const id=entry.target.getAttribute('id');navLinks.forEach(link=>{link.classList.toggle('active',link.getAttribute('href')==='#'+id);});}});},{threshold:0.3,rootMargin:'-80px 0px -40% 0px'});sections.forEach(s=>observer.observe(s));});document.addEventListener('DOMContentLoaded',()=>{const btn=document.getElementById('backToTop');if(!btn)return;window.addEventListener('scroll',()=>{btn.classList.toggle('visible',window.scrollY>400);},{passive:true});btn.addEventListener('click',()=>{window.scrollTo({top:0,behavior:'smooth'});});});document.addEventListener('DOMContentLoaded',()=>{const hint=document.getElementById('sliderHint');if(!hint)return;const isTouch=('ontouchstart'in window)||(navigator.maxTouchPoints>0);hint.textContent=isTouch?'Deslizá para comparar':'Arrastrá el divisor';});const _origSetSede=setSede;setSede=function(sedeKey){_origSetSede(sedeKey);applyServiceLinks();};document.addEventListener('DOMContentLoaded',()=>{applyServiceLinks();});(function(){const origSetSede2=setSede;setSede=function(sedeKey){origSetSede2(sedeKey);if(sedeKey==='vgg'){const iframe=document.querySelector('.mapFrame[data-sede="vgg"]');if(iframe&&iframe.dataset.src&&!iframe.getAttribute("src")){iframe.src=iframe.dataset.src;}}};})();const _origRender=renderReseñas;renderReseñas=function(){_origRender();const grid=document.getElementById('testimGrid');if(!grid)return;const cards=Array.from(grid.querySelectorAll('.testimCard'));if(cards.length<=6)return;cards.slice(6).forEach(c=>{c.style.display='none';c.dataset.hidden='1';});if(!document.getElementById('verMasBtn')){const btn=document.createElement('button');btn.id='verMasBtn';btn.className='btn';btn.textContent='Ver más reseñas ('+(cards.length-6)+')';btn.style.cssText='margin:16px auto 0;display:block;';btn.onclick=()=>{grid.querySelectorAll('[data-hidden]').forEach(c=>{c.style.display='';delete c.dataset.hidden;});btn.remove();};grid.parentNode.insertBefore(btn,grid.nextSibling);}};